#!/bin/bash

#$ -cwd -S /bin/bash -V
#$ -j y -o logs/
#$ -l gpu=1 -q gpu.q@@v100 -l h_rt=48:00:00

source /opt/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate fairseq

script=$1
modeldir=$2
shift
shift

echo "Running $script $modeldir $@"

if [[ -e $modeldir ]]; then
    echo "Refusing to run since $modeldir already exists"
    exit 1
fi

echo "See results $modeldir/log"

# Now we're on a GPU
bash $script $modeldir "$@" >> $modeldir/log 2>&1
