#!/bin/bash

#$ -cwd -S /bin/bash -V
#$ -j y -o logs/
#$ -l gpu=4 -q gpu.q@@v100 -l h_rt=168:00:00

source /home/hltcoe/esalesky/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate visrep

modeldir=$1
shift

echo "Training in $modeldir $@"

# Now we're on a GPU
# expects positional $modeldir $src $tgt ..params..
bash /exp/esalesky/visrep/fairseq-ocr/grid_scripts/train-big.sh $modeldir "$@"

echo "Done."
